### ISSUE TITLE
[Bug Report] An error will be reported if the plug-in is introduced into the project built by vue3 & vite

### ISSUE THREAD

**Issue by loafer-shu** [JamieCurnow/vue-clipboard3#2]
**The error message is:**
[vite:resolve] Failed to resolve entry for package "vue-clipboard3". The package may have incorrect main/module/exports specified in its package.json.
--

The specified es file was not found in the package published by NPM

I changed the 'module' field value 'src' to 'dist'  to temporarily solve this problem；

**Comment by JamieCurnow** [comment]
Hi @SeeTheDream, thanks for the bug report! I'll make a fix and push right now :)
