### ISSUE TITLE
The requested module '/node_modules/vue-clipboard3/dist/index.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by zhupengsheng** [JamieCurnow/vue-clipboard3#4]
"vue": "^3.2.4",
    "vite": "^2.7.2"

**Comment by JamieCurnow** [comment]
@qazwsx12345edc Thanks for the heads up! I'll push a fix ASAP.

**Comment by JamieCurnow** [comment]
@qazwsx12345edc This should be fixed now in new major version 2.0.0 with better support for esm modules 😃

**Comment by zhupengsheng** [comment]
This is an automatic reply confirming that your e-mail was received. Thank you!

**Comment by zhupengsheng** [comment]
This is an automatic reply confirming that your e-mail was received. Thank you!
